### ISSUE TITLE
Again :D

### ISSUE THREAD

**Issue by ghost** [Taylcd/ReportUI#10]
On validation after choose  the  player who i  want to report 

`$this->sendReasonSelect($sender);`

This function do not apair

**Comment by q1an1x** [comment]
Can you try describing the question more specifically? I really couldn't understand what you're saying.

**Comment by ghost** [comment]
They are 2 players
- ArmTheDev
- Steve

I do /report 
I choose to report Steve with the  DropDown
I click on sumite 
Nothing happen

I see on SendReport function normaly after choose the  target plugin send to player 
`$this->sendReasonSelect($sender);`

**Comment by q1an1x** [comment]
I don't really know why that happened on your server, it works perfectly fine last time I tested it, can you add this before line 180 and comment with the output?
`var_dump($data);`
