### ISSUE TITLE
Nukkit?

### ISSUE THREAD

**Issue by ghost** [Taylcd/ReportUI#13]
Why not and for nukkit ? :D

**Comment by ghost** [comment]
any answers?

**Comment by q1an1x** [comment]
This is a plugin for PocketMine and will not support nukkit.

**Comment by ghost** [comment]
I purpose you to create and for NukkitX 👍 

NukkitX have a biggest support for FormsAPI already, not need use other libraries 👍

**Comment by ghost** [comment]
Seriosly, you lenny to answer with yes or no? @Taylcd
