### ISSUE TITLE
THAT IS NO ISSUE!!!

### ISSUE THREAD

**Issue by ghost** [Taylcd/ReportUI#2]
Hello Taylcd, now i know how your Plugin works :) And i would find it awesome if you add a option that allows you to ban someone in the ReportGUI for time (tempban)!! That would be awesome!!
btw nice PL!!

**Comment by q1an1x** [comment]
What you're looking for is another tempban plugin, feel free to use search.

**Comment by ghost** [comment]
I have already a tempban plugin, but i mean, it would bei awesome If this option will be added to the GUI!! But thanks :)
