### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by BlockCraftMCPE** [Taylcd/ReportUI#4]
Hey, 
it would be very nice if you add MySQL to this so it can used on Many Servers and the reports are getting synchronized(Or how it is written,you know what i mean)
Regards,
BLOCKSTORM_

**Comment by BlockCraftMCPE** [comment]
Statement or Answer?

**Comment by q1an1x** [comment]
Hi there, thank you for the suggestion, but I don't really see the point if only reports are getting synchronized, I think what you needed more is a better user management plugin that supports multi-server.
